// Mock data for products (12 products total)
const allProducts = [
  {
    id: 1,
    name: "Digital Thermometer",
    category: "medicine",
    description: "Precision medical device",
    image: "assets/images/products/thermometer.png",
  },
  {
    id: 2,
    name: "Portable ECG Monitor",
    category: "electronics",
    description: "Advanced cardiac monitoring",
    image: "assets/images/products/ecg.png",
  },
  {
    id: 3,
    name: "Medical Stethoscope",
    category: "equipment",
    description: "Professional diagnostic tool",
    image: "stethoscope.png",
  },
  {
    id: 4,
    name: "First Aid Kit",
    category: "supplies",
    description: "Complete emergency supplies",
    image: "first-aid.png",
  },
  {
    id: 5,
    name: "Blood Pressure Monitor",
    category: "medicine",
    description: "Accurate readings at home",
    image: "blood-pressure.png",
  },
  {
    id: 6,
    name: "Pulse Oximeter",
    category: "electronics",
    description: "Measure oxygen saturation",
    image: "pulse-oximeter.png",
  },
  {
    id: 7,
    name: "Inhaler Device",
    category: "medicine",
    description: "For asthma and respiratory conditions",
    image: "inhaler.png",
  },
  {
    id: 8,
    name: "Glucose Monitor",
    category: "electronics",
    description: "Diabetes management tool",
    image: "glucose.png",
  },
  {
    id: 9,
    name: "Surgical Gloves",
    category: "supplies",
    description: "Sterile medical gloves",
    image: "gloves.png",
  },
  {
    id: 10,
    name: "Nebulizer Machine",
    category: "equipment",
    description: "Respiratory treatment device",
    image: "nebulizer.png",
  },
  {
    id: 11,
    name: "Thermometer Strips",
    category: "medicine",
    description: "Disposable temperature strips",
    image: "thermometer-strips.png",
  },
  {
    id: 12,
    name: "Defibrillator",
    category: "electronics",
    description: "Emergency cardiac device",
    image: "defibrillator.png",
  },
];
